// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/activities": {
    params: {};
  };
  "/activities/:activityId": {
    params: {
      "activityId": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/users/create": {
    params: {};
  };
  "/users/group/:userId": {
    params: {
      "userId": string;
    };
  };
  "/users/group/:userId/assign": {
    params: {
      "userId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/activities" | "/activities/:activityId" | "/users" | "/users/:userId" | "/users/create" | "/users/group/:userId" | "/users/group/:userId/assign" | "/*";
  };
  "./layout/global-layout.tsx": {
    id: "layout/global-layout";
    page: "/";
  };
  "./pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "./layout/main-layout.tsx": {
    id: "layout/main-layout";
    page: "/dashboard" | "/activities" | "/activities/:activityId" | "/users" | "/users/:userId" | "/users/create" | "/users/group/:userId" | "/users/group/:userId/assign";
  };
  "./pages/dashboard.tsx": {
    id: "pages/dashboard";
    page: "/dashboard";
  };
  "./pages/activities/activities.component.tsx": {
    id: "pages/activities/activities.component";
    page: "/activities";
  };
  "./pages/activities/activity.component.tsx": {
    id: "pages/activities/activity.component";
    page: "/activities/:activityId";
  };
  "./pages/users/users.component.tsx": {
    id: "pages/users/users.component";
    page: "/users";
  };
  "./pages/users/user.component.tsx": {
    id: "pages/users/user.component";
    page: "/users/:userId";
  };
  "./pages/users/create-user.component.tsx": {
    id: "pages/users/create-user.component";
    page: "/users/create";
  };
  "./pages/users/group.component.tsx": {
    id: "pages/users/group.component";
    page: "/users/group/:userId";
  };
  "./pages/users/group-assign.component.tsx": {
    id: "pages/users/group-assign.component";
    page: "/users/group/:userId/assign";
  };
  "catchall.tsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};